### ISSUE TITLE
@bem-react/di: Same interface for registry and registry of registry

### ISSUE THREAD

**Issue by yarastqt** [bem/bem-react#335]
```ts
const registry = registries.get('registry-key');
const Component = registry.get('component-key');
```

**Comment by awinogradov** [comment]
Now it's object and object after calling [`snapshot` method](https://github.com/bem/bem-react/blob/master/packages/di/di.tsx#L101). Added here https://github.com/bem/bem-react/commit/7890e033f82afeb82b52bb811e4423531b9e3705.
