### ISSUE TITLE
@bem-react/core: may be a compose bug

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react#337]
https://codesandbox.io/s/m54nq3nvmx

Steps:
1. Reorder args in `compose()` call like `ButtonTypeLink, ButtonThemeAction`
2. Look at the result > `<a class="Button Button_type_link">Hello</a>`

Expected:
`<a class="Button Button_type_link Button_theme_action">Hello</a>`

**Comment by awinogradov** [comment]
> Если B использует запись ModBody, то на нем все прервется и C уже не применится

Можешь показать код с воспроизведением такого поведения? 

Сейчас работает так, что результат modBody из B будет входным аргументов к C. Но если у тебя есть обратный кейс, покажи?

**Comment by Vittly** [comment]
А ты смотрел в ссылку, которая в самом начале?

Там у меня `<Button text="Hello" type="link" theme="action" />`, при этом "Button_type_link" реализован как `ModBody`, а "Button_theme_action" реализован без него.

Если я пишу `Button = compose(ButtonTypeLink, ButtonThemeAction)(Base)` - `ModBody` идет первым, то у меня получается на выходе только `<a class="Button Button_type_link">Hello</a>`. **Это проблема**

Если я пишу в обратном порядке `Button = compose(ButtonThemeAction, ButtonTypeLink)(Base)` - `ModBody` идет вторым, то у меня получается ровно то, что и хотелось - `<a class="Button Button_type_link Button_theme_action">Hello</a>`

**Comment by awinogradov** [comment]
@Vittly глянул ссылку, проморгал в первый раз. По твоему коду описанное как проблема поведение совершенно не проблема) Потому что в `Button_type_link` ты явно пересоздаешь класс, при этом забираешь только тот, что передан через внешний проп `className`. Как известно в `compose` вызов проходит справа налево, то есть в записи `compose(ButtonTypeLink, ButtonThemeAction)(Base)` первым вызывается `ButtonThemeAction`, где формируется JSX.Element, ты же в `Button_type_link` не вызываешь Base никак, а пересоздаешь целиком, поэтому и не приезжает класс. Он будет только при вызове через `<Base {...props}/>`. Другими словами, тебе надо унести в internal проп смену html-тега `<Base {...props} tag="a"/>`

**Comment by Vittly** [comment]
> в Button_type_link не вызываешь Base никак

наоборот в `Button_type_link` я использую `withBemMod` без дополнительных настроек и ожидаю, что "оно само все правильно сделает" - а именно помержит мне классы. Ведь обычно так и работает, а третий ургумент `callback` считается опциональным.

Понятно, что это не баг-баг, но пользователям может быть неудобно/неочевидно все это

**Comment by awinogradov** [comment]
Вот тест для воспроизведения.

``` tsx
it('should match on both matched prop', () => {
        const Enhanced1 = withBemMod<IPresenterProps>(presenter(), { theme: 'normal', url: '*' }, Base => props => (
            <Base {...[props]} className="Additional" />
        ))(Presenter);
        const Component = <Enhanced1 url="ya.ru" theme="normal" />;

        expect(getClassNameFromSelector(Component))
            .eq('Presenter Presenter_theme_normal Additional');
    });
```

**Comment by Vittly** [comment]
дошло, закрываю
