### ISSUE TITLE
@bem-react/core: Not pass matched props from withBemMod

### ISSUE THREAD

**Issue by yarastqt** [bem/bem-react#344]
Example:
```tsx
function Button({ type = 'button', ...props }) {
  return (
    <button
      {...props}
      type={type}
    />
  )
}

const withTypeLink = withBemMod('Button', { type: 'link' })
const ButtonEnhance = withTypeLink(Button)
const renderer = () => <ButtonEnhance type="link" />
```

Actual render:
```html
<button type="link" />
```

Expected render:
```html
<button type="button" />
```

**Comment by belozer** [comment]
`const renderer = () => <ButtonEnhance type="link" />`  возвращает `<button type="link" />`
Вроде логично. 

Точно верный Example?

**Comment by belozer** [comment]
Не понятна проблематика. Здесь точно бага? Вроде всё логично исходя из Example...

@yarastqt можешь объяснить почему `<ButtonEnhance type="link" />` должен генерировать `<button type="button" />` ?

**Comment by awinogradov** [comment]
Это никакой не баг, а нормальное поведение. У нас нет "специальных" пропов для матчинга. Пропы пробрасываются в компонент как и есть, что правильно. @yarastqt в примере ты пробрасываешь type и получаешь ожидаемый результат. В чем баг?
