### ISSUE TITLE
@bem-react/core: typings for ModBody & withBemMod

### ISSUE THREAD

**Issue by schemelev** [bem/bem-react#358]
https://codesandbox.io/s/0m05m4920

### case 1 ModBody
scr/components/Link/_type/Link_type_pseudo.tsx
```
const LinkPseudo: ModBody<ILinkProps> = (_Base, props) => {
    const { children, ...propsWithoutChildren } = props;

    return <span {...propsWithoutChildren}>{children}</span>;
};
```

In the `ILinkProps` interface, I must explicitly specify the standard props like `children`

### case 2 withBemMod
scr/components/Link/_type/Link_type_pseudo.tsx
```
export const LinkTypePseudo = withBemMod<ILinkProps>('Link', { type: 'pseudo' }, LinkPseudo);
```
The `ILinkProps` interface specifies a possible value for `type`, but here I can specify any.

For example, this code is built, but should not:
```
export const LinkTypePseudo = withBemMod<ILinkProps>('Link', { type: true }, LinkPseudo);
```

**Possible solution**
In line: https://github.com/bem/bem-react/blob/27410e4cc86d3b01c68ae37ed82fbb4508f0f43a/packages/core/core.tsx#L21
replace `mod: NoStrictEntityMods` with `mod: Partial<P>`

**Comment by awinogradov** [comment]
In case 1 we need to extend from `React.Props` interface  :( In case 2, I'll happy to see PR from you ;) Thank you so for this report! 🙏

**Comment by schemelev** [comment]
@awinogradov Maybe implement custom matcher: `mod: Partial<P> | (props: P) => likeBoolean`?

This will make it possible to implement a modifier with a large number of values. For example, the `Icon` component.

Or did I miss the way to express this case?

**Comment by awinogradov** [comment]
In the beginning, it was a function, we did shorter as a partial object of props. Maybe ModBody can support 2 variants of matcher: short and function. So, I have an abstract implementation of this behavior https://github.com/awinogradov/condicom.

**Comment by awinogradov** [comment]
@schemelev let's check #374 ;)
