### ISSUE TITLE
@bem-react/core: proposal for add additional modifier from withBemMod

### ISSUE THREAD

**Issue by yarastqt** [bem/bem-react#392]
## Проблема

Хочется иметь возможность добавлять дополнительный модификатор при включении другого.

Чтобы добавить дополнительный модификатор в рамках другого, приходится добавлять обертку в которой вновь создавать класс с модификатором (такие кейсы не единичны):

```tsx
withBemMod(cn(), { mod: 'val' }, (WrappedComponent) => ({
  className,
  ...props
}) => (
  <WrappedComponent
      {...props}
      className={cn({ addMod: 'val' }, [className])}
  />
))
```

## Предложение

Передавать модификаторы в `cn` первого аргумента:

```tsx
withBemMod(cn({ addMod: 'val' }), { mod: 'val' })
```

**Comment by zxqfox** [comment]
`cn.set('addMod')`
`cn.set({ name: 'addMod', val: 'val' })`

Может так?

**Comment by awinogradov** [comment]
А чем так плохо? И почему этому прям сейчас не заработать? 
``` js
withBemMod(cn({ modName: 'modVal' }), { mod: 'val' })
```

Но в таком случае динамические значения для таких модификаторов поддержены не будут.

**Comment by yarastqt** [comment]
Нужно проверить, если будет работать, то тест написать :)

**Comment by belozer** [comment]
Боюсь, что не заработает, т.к. сломается cn, в качестве имени блока будет задано `block block_addMod_val`

https://github.com/bem/bem-react/blob/master/packages/core/core.tsx#L13-L36

**Comment by yarastqt** [comment]
Из коробки не заработает, нужны доработки :)

**Comment by belozer** [comment]
Ну не знаю, как по мне, то решение в таком виде

```jsx
withBemMod(cn(), { mod: 'val' }, (WrappedComponent) => ({
  className,
  ...props
}) => (
  <WrappedComponent
      {...props}
      className={cn({ addMod: 'val' }, [className])}
  />
))
```

Выглядит более понятным и однозначным в прочтении. В добавок динамические модификаторы работают.

Ну либо так (массив модификаторов), но уже нет динамических.

`withBemMod(cn(), [{ mod: 'val' }, { modName: 'modVal' }])`

@yarastqt можем на конкретном примере привести зачем нужна такая штука?

**Comment by belozer** [comment]
Но на счёт массива вообще, полезна такая штука, как по мне.

```tsx
export const withHasDiscount = withBemMod<PriceHasDiscountPriceProps, PriceProps>(cnPrice(), [{
    // Условия
    hasDiscount: '*',
    discount: '*', // условие 1
    value: val => val > 100, // условие 2
}, {
    hasDiscount: true, // установка модификатора
    otherMod: true, // установка модификатора
}], Price => {
    // после выполнения условий
});
```

@yarastqt

**Comment by yarastqt** [comment]
На текущий момент у нас осталось только одно место в котором есть подобное использование и кажется, что это не особо и нужно, не хочется усложнять API в данном месте. Ишью пока что закрываю, т.к. нету кейсов.
