### ISSUE TITLE
compose looks only to first two arguments

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-react#394]
compose({}, {}, props}

not the  same as

compose(props, {}, {})

**Comment by yarastqt** [comment]
Предлагаю сделать вариант, который хотели сделать первоначально _(т.к. все равно не получается использовать все модификаторы в рамках одной композиции)_ — экспортировать два типа `compose`:

* `composeU` — для union
* `composeI or compose` — для intersection

**Comment by yarastqt** [comment]
Проблема возникает так же в таком кейсе:

```
interface Theme1Props {
  theme: '1',
  prop1?: string,
}

interface Theme2Props {
  theme: '2',
  prop2?: string,
}
```

В итоге проверка:
https://github.com/bem/bem-react/blob/b282e7d73fdb46db8c9e4fb53fb41f481ef7bb38/packages/core/core.tsx#L110
Работает не корректно и мы получаем пересечение вместо объединения

**Comment by Vittly** [comment]
Я плюсую за два композа, но:
1. Лучше сделать `composeUnion` и `composeIntersection` (а короткие варианты только как алиасы)
2. Стоит сделать просто `compose`, который сейчас - так как часто его хватает и не надо знать про `&` и `|` в типах

**Comment by Vittly** [comment]
это кстати про тоже самое - https://github.com/bem/bem-react/issues/365

**Comment by Vittly** [comment]
прикольно:
- если просто разные значения модификатора [то ок](https://www.typescriptlang.org/play/index.html#src=interface%20T1%20%7B%0D%0A%20%20theme%3A%20'1'%0D%0A%7D%0D%0A%0D%0Ainterface%20T2%20%7B%0D%0A%20%20theme%3A%20'2'%0D%0A%7D%0D%0A%0D%0Atype%20T%20%3D%20keyof%20T1%20extends%20keyof%20T2%20%3F%20T1%20%7C%20T2%20%3A%20T1%20%26%20T2%3B%0D%0A%0D%0Alet%20x%3A%20T%20%3D%20%7B%20theme%3A%20'1'%20%7D%3B%20)
- если появляется дополнительное поле [то все ломается](https://www.typescriptlang.org/play/index.html#src=interface%20T1%20%7B%0D%0A%20%20theme%3A%20'1'%2C%0D%0A%20%20prop1%3F%3A%20string%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20T2%20%7B%0D%0A%20%20theme%3A%20'2'%2C%0D%0A%20%20prop2%3F%3A%20string%2C%0D%0A%7D%0D%0A%0D%0Atype%20T%20%3D%20keyof%20T1%20extends%20keyof%20T2%20%3F%20T1%20%7C%20T2%20%3A%20T1%20%26%20T2%3B%0D%0A%0D%0Alet%20x%3A%20T%20%3D%20%7B%20prop1%3A%20'x'%2C%20prop2%3A%20'y'%2C%20theme%3A%20'1'%20%7D%3B%20)
