### ISSUE TITLE
withBemMod enhancement proposal

### ISSUE THREAD

**Issue by Frozik** [bem/bem-react#395]
In **withBemMod**

instead of
```
const modifierClassName = entity(Object.keys(mod).reduce((acc: Dictionary, key) => {
    if (mod[key] !== '*') acc[key] = mod[key];
```
use value for modifier from props
```
const modifierClassName = entity(Object.keys(mod).reduce((acc: Dictionary, key) => {
    acc[key] = mod[key] !== '*' ? mod[key] : props[key];
```

**Comment by yarastqt** [comment]
Привет! В оригинальном `i-bem` стеке насколько я помню было именно такое поведение, к тому же предикат на все значения это скорее редкий кейс, в любом случае ты можешь добавить такой модификатор в ХОКе:

```js
withBemMod('Block', { theme: '*' }, (Wrapped) => (
  ({ theme, ...props }) => (
    <Wrapped {...props} className={`Block_thene_${theme}`} />
  )
))
```

Но если сделать по умолчанию, то, что предложил ты - это уже никак нельзя будет отменить, придется заново создавать весь `className`.

**Comment by Frozik** [comment]
Да вот как раз не хочется добавлять и усложнять свой код ради такой мелочи, хочется чтобы все автоматически было. Может можно тогда использовать другие символы не входящие в css имена классов, & - вполне было бы логично?

**Comment by yarastqt** [comment]
А можешь рассказать, какую проблемы ты пытаешься решить? Просто кажется, что это какое-то точечное решение, если так, ты вполне можешь написать свою обертку, которая будет делать то, что тебе нужно.

**Comment by Frozik** [comment]
Может я не правильно готовлю, но я хочу иметь свойство типа theme которое принимает сразу несколько четко определенных значений - "theme1", "theme2", "theme3" у меня есть модификатор **withBemMod('Block', { theme: '*' }, Wrapped)** я хочу чтобы мне не надо было прописывать className постоянно, хочу чтобы значение бралось из props, ведь для конкретного значения это работает, почему тогда не может для нескольких четко определенных?

**Comment by awinogradov** [comment]
Я правильно понимаю, что у тебя есть несколько значений модификатора, которые делают одно и тоже? Почему это не одно значение? А если они делают разное, то почему плохо им быть разными файлами/хоками?

**Comment by awinogradov** [comment]
@Frozik ping

**Comment by belozer** [comment]
Прилинкую эту issue #374, т.к. она была именно об этом, на сколько я понимаю.

**Comment by belozer** [comment]
Почему бы не сделать специальные константы в качестве решения?

```
import { SILENT_MOD } from '@bem-react/core'

withBemMod('Block', { url: SILENT_MOD }, Block => props => (
  <Block {...props} tag='a'>
))

<Block url='https://yandex.ru' />
// <a class='Block'></a>
```

```
withBemMod('Block', { theme: '*' })

<Block theme='dark' />
// <div class='Block Block_theme_dark'></div>
```

@awinogradov @Frozik

**Comment by awinogradov** [comment]
Кажется, что `withBemMod('Block', { theme: '*' })` покрывает все кейсы. @belozer чем `withBemMod('Block', { url: SILENT_MOD })` будет лучше, кроме явной именованной константы в коде?

**Comment by belozer** [comment]
@awinogradov проблема в интуитивности кода.

```js
withBemMod('Block', { theme: 'light' })
<Block theme='light' />
// <div class='Block Block_theme_light'></div>
```

```js
withBemMod('Block', { theme: '*' })
<Block theme='light' />
// <div class='Block'></div>
```

`*` - практически везде означает любое значение. И здесь во втором случае звёздочка тоже принимает любые значения. Это ок.

Но в первом случае конструкция вида `withBemMod('Block', { theme: 'light' })` добавляет класс, а во втором `withBemMod('Block', { theme: '*' })` нет. 

По мне - это неявное поведение, если не знать особенности.

Вариант с константой мне тоже не особо нравится, как альтернативу думал ещё ипользовать функции (типо match из bemxjst)

```
withBemMod('Block', (props) => props.theme)
```

Или даже наиболее правильно вынести в отдельную штуку типа `withConditional` (или `withProps`)
```js
withConditional({ theme: 'light' }, (Block) => {}) // только шаблон
withBemMod('Block', { theme: 'light }, (Block) => {}) // шаблон + селектор
```
Таким образом мы получаем два разных хока, которые имеют однозначное поведение

**Comment by awinogradov** [comment]
@belozer Я думал сделать предикаты импортируемыми функциями. Тогда все будет работать как тв хочешь, но кажется, нас с тобой маловато и большинство случаев укладывается в стандартные матчеры. Посмотри у меня пакет condicom ;)

**Comment by belozer** [comment]
@awinogradov да, как раз хотел прикрепить ссылку на него. Не успел ))
https://github.com/awinogradov/condicom

Ну в общем и кейс пока со `*` тоже редкий кейс, который вызывает вопросы. Возможно в каком-то мажоре можно будет перейти на другие способы (если будут ещё запросы от людей).

**Comment by belozer** [comment]
@awinogradov кстати пакет `condicom` возможно можно бы и в `bem/bem-react` положить. Полезно для всяких `css-in-js` решений.

**Comment by awinogradov** [comment]
@belozer Да, на его основе выражается все что угодно. В том числе и модификаторы. Мы подумаем ;)

**Comment by yarastqt** [comment]
Закрываю ишьюс, т.к. решили, что такое поведение валидное и менять его не будем.
