### ISSUE TITLE
@bem-react/di: добавить возможность типизировать  множество ключей компонентов, которые хранятся в регистре

### ISSUE THREAD

**Issue by devsnice** [bem/bem-react#397]
В текущей реализации, компоненты хранятся в регистре с интерфейсом
```
interface IRegistryComponents {
    [key: string]: any;
}
```

Предлагаю добавить возможность типизировать множество ключей, чтобы при использовании можно было избежать ошибок:

1. указания неправильного названия ключа (опечатки, и т.д)
2. повтора ключей в регистре

Это позволит хранить интерфейс в одном месте и удобно работать с этим в клиентском приложении, уменьшить количество ошибок и улучшить поддерживаемость кодовой базы

**Пример использования**

registry.ts
```
export enum PlatformComponentsEnum {
  'Header' = 'Header',
  'MainSlider' = 'MainSlider'
}

const platformRegistry = new Registry<PlatformComponentsEnum>({ id: APP_PLATFORM_REGISTRY });
```

app.tsx
```
 {registry => {
      const Header = registry.get(PlatformComponentsEnum.Header);

      return (
          <Header />
      );
 }}
```

**Comment by yarastqt** [comment]
Привет! Сейчас уже реализовано нечто похоже в типизированном консьюмере `ComponentRegistryConsumer`, но только не через enum. Вот пример:

```tsx
interface IComponentRegistry {
  Control: typeof Control
}

<ComponentRegistryConsumer id={cn()}>
  {({ Control }: IComponentRegistry) => (
      <Control />
  )}
</ComponentRegistryConsumer>
```

Если же тебе нужно использовать внутри компонента несколько реестров, ты можешь использовать снепшот реестра передав ему дженерик:

```ts
interface IComponentRegistry {
  Control: typeof Control
}

const registry = registries[cn()]
const { Control } = registry.snapshot<IComponentRegistry>()
```

Так же у нас есть задача на то, чтобы проверять правильность устанавливаемых ключей на основании интерфейса: #386

**Comment by yarastqt** [comment]
@devsnice Тебе подходит такое решение? :)

**Comment by yarastqt** [comment]
@devsnice ping

**Comment by yarastqt** [comment]
Закрываю, т.к. нету никакой активности, если есть что-то, то давай в #386
