### ISSUE TITLE
@bem-react/classname: support css modules

### ISSUE THREAD

**Issue by apoleshchuk** [bem/bem-react#398]
In some cases need encapsulation for css styles (for emdeded code, etc.).

#267 issue about support in old version.

**Comment by yarastqt** [comment]
Hello, you have any idea how implement ccs modules for current architecture?

We also have configure `@bem-react/classname` with custom namespace:

```ts
import { withNaming } from '@bem-react/classname'

const cn = withNaming({ n: 'Y', e: '-', m: '_' })
const className = cn('Button')() // => YButton
```

**Comment by apoleshchuk** [comment]
No, but @awinogradov will answer «it's possible, but required modify current code».

**Comment by awinogradov** [comment]
Yep, we can make object of selectors as valid argument for cn function
