### ISSUE TITLE
@bem-react/di: withRegistry не корректно очищается при переопределении компонентов

### ISSUE THREAD

**Issue by WalkInWay** [bem/bem-react#400]
Если переопределить компонент, у которого есть registry, то первоначальный родительский компонент пытается использовать переопределёные свойства из registry дочернего компонента.

Предположительное место, где что-то не так: https://github.com/bem/bem-react/blob/master/packages/di/di.tsx#L22

**Comment by yarastqt** [comment]
Привет! А сможешь собрать демку с проблемой? К примеру на https://codesandbox.io/

**Comment by yarastqt** [comment]
Либо написать тут минимальный пример для воспроизведения

**Comment by WalkInWay** [comment]
Привет! 
А как собрать Демку? Есть где-то пример минимального кода, чтобы создать и вывести компонент на страницу с нуля?

**Comment by yarastqt** [comment]
Сделал пустой проект https://codesandbox.io/s/jn32joox43, добавил сюда все зависимости из `@bem-react/*`, можешь взять за основу его

**Comment by artems** [comment]
Пример
https://codesandbox.io/s/y2v7xyylz1
