### ISSUE TITLE
@bem-react/di: Proposal add React hooks for component registry

### ISSUE THREAD

**Issue by stenin-nikita** [bem/bem-react#405]
## Предложение

Предлагаю добавить React хуки для работы с реестром компонентов. Пример, как это может выглядеть:

```typescript
const Button = () => {
  const { Text } = useComponentRegistry(cnButton());

  return <Text />
}
```

вместо:

```typescript
const Button = () => {
  return (
    <ComponentRegistryConsumer id={cnButton()}>
      {({ Text }) => (
        <Text />
      )}
    </ComponentRegistryConsumer>
  );
}
```

Рабочий пример можно посмотреть в [codesandbox](https://codesandbox.io/s/lr3lqryn0z?fontsize=14)

Возможно будет лучше сделать это отдельным пакетом. На данный момент мешает то, что в `@bem-react/di` не экспортируется контекст.

**Comment by yarastqt** [comment]
Норм, но отдельным пакетом не стоит делать, т.к. все пакеты атомарные

**Comment by awinogradov** [comment]
Давайте сделаем

**Comment by yarastqt** [comment]
Займусь этим

**Comment by stenin-nikita** [comment]
👍
