### ISSUE TITLE
@bem-react/classname Разделитель для ключ-значения модификатора

### ISSUE THREAD

**Issue by dimensi** [bem/bem-react#413]
Привет, можете добавить в withNaming 4 параметр который будет отвечать за разделитель между модификатором и его ключом.
Я использую примерно такой стиль по именованию, только для ключа использую свой разделитель, выглядит это примерно так:
`block-name__element-name--mod-name_key-name` (это самый длинный вариант)
А так реальный кейс это `Surfer__img--type_wave`
Я раньше использовал вот эту библиотеку https://github.com/c01nd01r/vue-bem-cn#q-i-will-want-use-another-delimiters-for-bem-entities-and-still-i-need-namespances, но так как я теперь на другом фреймворке, то просто перешел на ваше решение.

**Comment by yarastqt** [comment]
Привет! Не особо понял про 4-й параметр, судя по тому, что ты хочешь, тебе нужно указать при конфигурации нужный разделитель:

```js
const cn = withNaming({ e: '__', m: '--' })
```

Вот пример — https://codesandbox.io/s/pyjnp08nq0

**Comment by dimensi** [comment]
Параметр, который будет отвечать за разделитель между модификатором ключом и модификатором значением. 
В вашем примере `Block--theme--normal`, а не `Block--theme_normal`

**Comment by yarastqt** [comment]
Все, понял, в целом кажется это не так сложно сделать, постараюсь добраться до этого в скором времени :)

**Comment by dimensi** [comment]
Спасибо
