### ISSUE TITLE
No export ModBody from @react-bem/core

### ISSUE THREAD

**Issue by Arelav** [bem/bem-react#414]
I'm trying to use @react-bem/core as documented however there is no export `ModBody` from `@react-bem/core`

However i have the error from this import `import { withBemMod, ModBody } from '@bem-react/core';`

{
	"resource": "/Users/MY_USERNAME/projects/playground/bem-react-demo/src/shared/components/Button/_type/Button_type_link.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"../../../../../../../../../../Users/MY_USERNAME/projects/playground/bem-react-demo/node_modules/@bem-react/core/core\"' has no exported member 'ModBody'.",

I can find `withBemMod` in `core.d.ts` however no `ModBody`

**Comment by tadatuta** [comment]
it's `Enhance` now

**Comment by Arelav** [comment]
Thanks for a quick update.
