### ISSUE TITLE
@bem-react/core бага, либо устарела дока

### ISSUE THREAD

**Issue by belozer** [bem/bem-react#418]
https://github.com/bem/bem-react/blob/master/packages/core/core.tsx#L37-L40

Здесь чистится строка класса. В следствии чего кейс из примера (в README) становится не валидным, т.к. при установке модификатора `_type_link` в классе получаем только модификаторы без класса самого блока.

```tsx
const withButtonTypeLink = withBemMod('Button', { type: 'link' }, (Button) => (
  ({ text, className }) => (
    <a className={className}>{text}</a>
  )
));
```
```tsx
const ButtonWithMods = compose(withButtonTypeLink)(Button);
(<ButtonWithMods type='link' />)
```

Результат
```html
<a class='Button_link'></a>
```

Возможно стоит править пример, например так.
```tsx
const withButtonTypeLink = withBemMod('Button', { type: 'link' }, (Button) => (
  ({ text, className }) => (
    <a className={cnButton(null, [className])}>{text}</a>
  )
));
```
либо вернуть чистку дубликатов в сам `cn`

П.Н.
Да и step-2 кажется тоже не корректен, т.к. нет базового класса блока.

@awinogradov

**Comment by yarastqt** [comment]
Нужно в readme поправить пример, правильней будет сделать так:

```tsx
const Button = ({ tag: TagName, className, children }) => (
  <TagName className={className}>
    {children}
  </TagName>
)

const withButtonTypeLink = withBemMod('Button', { type: 'link' }, (Button) => (props) => (
  <Button {...props} tag="a" />
))
```
