### ISSUE TITLE
withBemMod: Не ставится модификатор при синтаксисе { modName: '*' }

### ISSUE THREAD

**Issue by elite174** [bem/bem-react#422]
В случае `A = withBemMod(cnA(), { mod: 'a' }, ...)` у компонента А в итоге будут классы: `А А_mod_a`
Но если написать `A = withBemMod(cnA(), { mod: '*' ), ...`, то у компонента А будет только класс `А`, а не `A A_mod`

**Comment by elite174** [comment]
И может, вместо 1 параметра `{mod: value | '*' }` сделать 2 параметра?
1. предикат, который определяет ставить модификатор или нет `(props: P) => boolean`
2. объект с выставляемыми модификаторами

Сейчас модификаторы ставятся по логике: или проп === значению или он есть (но тут баг), а что если я хочу ставить модификатор в зависимости от условия? Например, есть компонент, который принимает в качестве пропа целочисленный параметр. И необходимо ставить модификатор только в том случае, если этот параметр больше 15. Сейчас реализовать такую логику возможно только сравнением этого параметра сверху: `p>15? <A mod='value'/> : <A />`.

**Comment by yarastqt** [comment]
По первому вопросу уже обсуждали — #395, можно продолжить обсуждение там
По второму вопросу есть также ишьюс — #381, в котором хотим сделать возможность передавать в качестве второго аргумента предикат, а не объект
