### ISSUE TITLE
Old version on NPM

### ISSUE THREAD

**Issue by Amedomary** [bem/bem-react#425]
dont have mod-value in nmp
https://www.npmjs.com/package/@bem-react/classname

**Comment by yarastqt** [comment]
Можешь подробнее расписать проблему? :)

**Comment by Amedomary** [comment]
@yarastqt  В нпм версии нет значения v:
mod_value 
только мод. 
а на гитхабе есть.

**Comment by awinogradov** [comment]
```
Successfully published:
 - @bem-react/classname@1.5.0
 - @bem-react/classnames@1.3.2
 - @bem-react/core@1.6.5
 - @bem-react/di@1.6.0
```
