### ISSUE TITLE
Как работать с компонентами-контейнерами?

### ISSUE THREAD

**Issue by remnev** [bem/bem-react#430]
Привет. Подскажите, как архитектурно подразумевается работать с компонентами, у которых есть вью- и управляющая части.

Например, базовый компонент:
```
Payment/
    Payment.container.tsx
    Payment.tsx
```

и я хочу реализовать модификацию:
```
_hasEnhancement/
    Payment_hasEnhancement.tsx
```

в модификации добавляется кнопка, клик по которой должен где-то обрабатываться, например в `Payment_hasEnhancement.container.tsx`, т.е. должно стать так:
```
_hasEnhancement/
    Payment_hasEnhancement.tsx
    Payment_hasEnhancement.container.tsx
```

В этом месте я не понимаю как реализовать этот управляющий компонент, чтобы все базовые обработчики взялись из Payment.container.tsx (и там же подлючение к redux-стору) и сверху на это наклеился обработчик нажатия кнопки из Payment_hasEnhancement.tsx. И чтобы внутри оказался Payment_hasEnhancement, а не просто базовый Payment.

**Comment by awinogradov** [comment]
Если я всё правильно понял (есть сомнения), то идея изначально не правильная. Контейнеры на то и контейнеры, чтобы управлять компонентом. Модификаторы существуют на уровне компонента, но не контейнера. То есть все необходимые модификаторы должны быть применены к моменту управления.

Условно:

``` ts

const Button = compose(withThemeNormal, withSizeS)(ButtonBase);

export const connectedButton = connect(
  mapStateToProps,
  mapDispatchToProps
)(Button);
```
