### ISSUE TITLE
Поправить ссылки на сайте bem.info

### ISSUE THREAD

**Issue by Krepish** [bem/bem-react#443]
На этой странице: https://ru.bem.info/technologies/bem-react/
не работают ссылки:
![image](https://user-images.githubusercontent.com/1763725/59845234-91e20700-9365-11e9-9bbf-78600b0ef537.png)

**Comment by yarastqt** [comment]
Но ведь bem.info это же другой репозиторий :)

**Comment by Krepish** [comment]
Ссылка,  по которой нужно репортить ошибки ведет на это репо :) 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/1763725/59969081-3030c100-954e-11e9-8ee3-2a336dda0f20.png)
