### ISSUE TITLE
withBemMod removes className if it matches blockName

### ISSUE THREAD

**Issue by nanot1m** [bem/bem-react#444]
**How to reproduce**
```jsx
import {Button} from 'my-super-ui-kit/Button';

const MyButton = withBemMod('MyButton', { theme: 'secondary' })(Button);

<MyButton className="MyButton" theme="secondary" />;
```

**Expected behaviour**
It renders Button with className `MyButton MyButton_theme_secondary`

**Actual behaviour**
It renders Button with className `MyButton_theme_secondary `

Problem somewhere here https://github.com/bem/bem-react/blob/master/packages/core/core.tsx#L41

**Comment by belozer** [comment]
@nanot1m please check docs https://github.com/bem/bem-react/tree/master/packages/core

you need use
```js
import {Button} from 'my-super-ui-kit/Button';

const withButtonThemeSecondary = withBemMod('MyButton', { theme: 'secondary' });

...

const MyButton = compose(withButtonThemeSecondary)(Button);

<MyButton className="MyButton" theme="secondary" />;
```

**Comment by nanot1m** [comment]
@belozer thanks for your response

But it does not help. `compose` only pipes functions and does not modify them

**Comment by awinogradov** [comment]
Firstly, you need to describe MyButton correctly

``` js
import { cn } from '@bem-react/classname';

const cnMyButton = cn('MyButton');

const MyButton = props => <button className={cnMyButton(null, [props.className])} />
```

`withBemMod` uses this part `cnMyButton(null, [props.className]`. The first argument is the static mods, the second one is the mixes. In your example, you don't have this part to provide extra mixes.

**Comment by belozer** [comment]
@nanot1m please check next steps

Step 1

```jsx
// ./Button/Button.jsx
import React from 'react';
import {cn} from '@bem-react/classname';

export const cnButton = cn('Button');

export const Button = ({ children, className }) => (
  <button className={cnButton({}, [className])}> 
    {children}
  </button>
);
```

Step 2
```jsx
// ./Button/_theme/Button_theme_secondary.jsx

import {withBemMod} from '@bem-react/core';
import {cnButton} from '../Button';

export const withButtonThemeSecondary = withBemMod(cnButton(), { theme: 'secondary' });
```

Step 3

```jsx
// Another code
import {compose} from `@bem-react/core`;
import {Button as ButtonPresenter} from './components/Button/Button';
import {withButtonThemeSecondary} from './components/Button/_theme/Button_theme_secondary';


const Button = compose(withButtonThemeSecondary)(ButtonPresenter)

// ...

<Button theme="secondary" />;
```

**Comment by nanot1m** [comment]
In my case Button is external component. And I can not change it

**Comment by awinogradov** [comment]
This fact means you need to open issue in `'my-super-ui-kit/Button'`

**Comment by awinogradov** [comment]
Let's check specs to find your situation https://github.com/bem/bem-react/blob/master/packages/core/test/withBemMod.test.tsx

**Comment by belozer** [comment]
@nanot1m 

> In my case Button is external component. And I can not change it

You can try modify first step as

```jsx
// ./Button/Button.jsx
import React from 'react';
import {cn} from '@bem-react/classname';
import {Button as ExternalButton} from 'my-super-ui-kit/Button';

export const cnButton = cn('Button');

export const Button = (props) => (
  <ExternalButton ...props className={cnButton(null, [props.className])} />
);
```

**Comment by nanot1m** [comment]
> Let's check specs to find your situation https://github.com/bem/bem-react/blob/master/packages/core/test/withBemMod.test.tsx

In all test cases className is the same as in presenter component. 

Is it not possible to give another `className` to external component and use `withBemMod` with this `className`?

**Comment by nanot1m** [comment]
@belozer it looks like workaround! thanks!

**Comment by awinogradov** [comment]
Check `cn` docs in usage section and try to pass smth by className prop https://github.com/bem/bem-react/tree/master/packages/classname#usage
