### ISSUE TITLE
@bem-react/classname: Микс со значением false не применяется

### ISSUE THREAD

**Issue by AleynikovSergey** [bem/bem-react#445]
В последнем минорном обновлении изменилось api, в результате при передаче falsey выбрасывается exception. Давайте такое поведение оставим на мажорное обновление, а сейчас будем выбрасывать warning с сообщением, что такой вариант использования в скором времени будет deprecated.

**Comment by belozer** [comment]
@AleynikovSergey что за `falsay` модификатор? Можешь пример скинуть?

**Comment by AleynikovSergey** [comment]
`showError && chField('Error')`

**Comment by yarastqt** [comment]
Привет, не совсем понятно о каком обновлении идёт речь, за последнее время в пакете `classname` не было никаких мажорных изменений, можешь привести полный пример кода и ошибку которую ты получаешь а итоге?

**Comment by AleynikovSergey** [comment]
У нас в проекте использовался `bem-react/classname` версии `1.1.1`, недавно мы решили обновить до версии `1.5.0`. После обновления во многих местах мы начали получать следующие ошибки. 
Вот пример кода, в котором происходит ошибка: 
```
<PriceInput
    className={
        ((forceShowValidationError || touched) && error) && cnPriceInput('Error')
    }
/>
```
Код ошибки:
```
Uncaught TypeError: value.split is not a function
    at eval (webpack-internal:///./node_modules/@bem-react/classname/build/cjs/classname.development.js:31)
    at Array.forEach (<anonymous>)
    at stringify (webpack-internal:///./node_modules/@bem-react/classname/build/cjs/classname.development.js:28)
    at eval (webpack-internal:///./node_modules/@bem-react/classname/build/cjs/classname.development.js:68)
    at PriceInputPresenter.render (webpack-internal:///./src/components/PriceInput/PriceInput.tsx:111)
    ...
```
В результате изменения api нам приходится приводить каждый вызов к такому виду, а таких мест у нас много: 
```
<PriceInput
    className={
        ((forceShowValidationError || touched) && error) ? cnPriceInput('Error') : ''
    }
/>
```
Такое изменение тянет на изменение в мажорной версии, а никак не в минорной. В минорных версиях следует пробрасывать варнинги о скором изменении api, чтобы разработчики успели подготовить свою кодовую базу к обновлению.

**Comment by belozer** [comment]
@AleynikovSergey а вы React 15 используете? Или 16?

React 16 во всю ругается на `<div className={false}></div>` и такие кейсы явно не уместны.
Да и то, что можно было использовать `false` в миксах кажется больше багой, чем фичей.

Имхо, лучше потратить пару часиков и прогуляться по проекту, чем забивать на это.

@awinogradov ты что скажешь?

**Comment by yarastqt** [comment]
Нужно добавить поверку на false значение тут — https://github.com/bem/bem-react/blob/master/packages/classname/classname.tsx#L92

**Comment by yarastqt** [comment]
Так, стоп, дак у нас явно был указан интерфейс о том, какие свойства мы ожидаем в миксе:
https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L6

К тому же миксы добавлять через условие как-то не совсем правильно, скорее всего тут какая-то архитектурная проблема, давай попытаемся разобраться, как можно улучшить. У тебя есть такой код:

```js
<PriceInput
    className={
        ((forceShowValidationError || touched) && error) ? cnPriceInput('Error') : ''
    }
/>
```

 Пример:

Тебе нужен какой-то доп. визуал при ошибке, соответственно у тебя должен быть компонент, к примеру `FormField` который является лейаутом, и у него должно быть свойство `error`, при наличии этого свойства можно добавлять модификатор на инпут или сам лейаут:

```js
const FormField = ({ error }) => (
  <>
    <input className={cn('Input', { invalid: Boolean(error) })} />
    {error && <span>{error}</span>}
  <>
)
```

**Comment by AleynikovSergey** [comment]
Даже если так. 
Но мы использовали версию `1.1.1`, при обновлении до `1.5.0`, что является минором, весь код ломается, что недопустимо, т.к. минорные апдейты не должны ломать код, который использовал предыдущую версию.

**Comment by belozer** [comment]
@AleynikovSergey вы писали заранее забагованный код.

Вот версия `classname@1.1.1`. Здесь явно указано, что используются только `string | undefined`.
https://github.com/bem/bem-react/blob/bem-react%404.2.0/packages/classname/classname.tsx#L40

В api пакета ничего не поменялось. Нет смысла делать мажор.

Как и писал уже ранее https://github.com/bem/bem-react/issues/445#issuecomment-509407400
Просто почистите проект от багов и всё, либо используйте `classname@1.1.1`

**Comment by DavyJohnes** [comment]
Давайте подойдем с другой стороны. Я не репорчу баг, я реквестую фичу.
В моем коде очень часто встречаются такие конструкции: 
`myCn(null, [this.props.transitionClassname])`, где интрефейс `this.props` такой: 
```
interface Props {
  transitionClassname?: string;
}
``` 
Я не хочу в каждом таком месте проверять `transitionClassname` на falsy и давать дефолтное значение, поскольку в масштабе на всю кодовую базу это добавит прилично лишнего кода.

Какие у меня есть варианты:
1. Написать свою обертку над `cn`, которая будет проверять передаваемые `mix`'ы на falsy и фолбэчится на пустую строку.
2. Реквестнуть фичу в библиотеке `cn`, так как чисто гипотетически, кейс довольно популярный и будет удобно не таскать упомянутую выше обертку от кода к коду, а иметь такое поведение из коробки.

Что скажете?

**Comment by personaljs** [comment]
Поддержу предыдущего парня, сейчас в конструкции `myCn(null, [this.props.transitionClassname])`, если `transitionClassname` не определен, на выходе мы получим `.class.undefined`.

**Comment by yarastqt** [comment]
Что-то не сходится, не должно получаться `.class.undefined`, т.к. есть явная проверка:
https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92
И о каких фолбеках идёт речь?

**Comment by belozer** [comment]
Давайте исходит из источника проблемы.

@AleynikovSergey я так понимаю, что ты не используешь TS. Верно? 
Т.к. иначе бы не было кейсов с `false` (т.к. редактор на это мгновенно ругается).

Проблема кроется в том, что кто-то использует `bem-react` без типизации.

@yarastqt чтобы всё работало правильно достаточно просто поправить условие
с `if (value !== undefined) { ` на `if (typeof value === 'string') {`, т.к. `forEach` и так пропускает `undefined`

По типизации всё ок, ничего не нужно мудрить.

В `else` можно запихнуть warning для тех кто пытается закинуть туда `number`, `null`, `false` и т.д.

Таким образом мы не делаем дополнительных проверок. Для тех кто пишет на TS дальше условия `if` вызов не пройдёт.

@AleynikovSergey  @DavyJohnes @personaljs как вам такое решение?

**Comment by AleynikovSergey** [comment]
@belozer, в проекте используется TS, но редактор не ругался, а ошибка получается только в рантайме.

**Comment by yarastqt** [comment]
@AleynikovSergey Это странно, если у тебя правильно объявлена сигнатура, то `false` значение, никак не может попасть, вот пример:
https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBACgTgezAZygXigbwFBSgYwBsBDZZAOWIFsIB+ALimWDgEsA7Ac2wF9tsAJhCLE40AGYBXdvmCsE7KAGEEVMAojtgACjCIUjeEmQBKRgDcErAfxVqNW7ZgIkylGo3HFCyaADI-KAByc29JCCCoHhMgA

**Comment by DavyJohnes** [comment]
> @AleynikovSergey Это странно, если у тебя правильно объявлена сигнатура, то `false` значение, никак не может попасть, вот пример:
> https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBACgTgezAZygXigbwFBSgYwBsBDZZAOWIFsIB+ALimWDgEsA7Ac2wF9tsAJhCLE40AGYBXdvmCsE7KAGEEVMAojtgACjCIUjeEmQBKRgDcErAfxVqNW7ZgIkylGo3HFCyaADI-KAByc29JCCCoHhMgA

Вся проблема в том `strictNullCheckL: false`.

**Comment by DavyJohnes** [comment]
@belozer @yarastqt а почему бы вот в этом месте https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92 не изменить на `if (value) {` и тогда это решить все наши проблемы?

**Comment by belozer** [comment]
> @belozer @yarastqt а почему бы вот в этом месте
> 
> https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92
> 
> не изменить на `if (value) {` и тогда это решить все наши проблемы?

@DavyJohnes потому-что, кто-то (не использующий TS) может запихнуть туда `null, number, true` и т.д.

**Comment by DavyJohnes** [comment]
> > @belozer @yarastqt а почему бы вот в этом месте
> > https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92
> > 
> > не изменить на `if (value) {` и тогда это решить все наши проблемы?
> 
> @DavyJohnes потому-что, кто-то (не использующий TS) может запихнуть туда `Number, true` и т.д., а так мы явно проверяем на `string`. Я как раз писал именно об этом месте ([#445 (comment)](https://github.com/bem/bem-react/issues/445#issuecomment-510974814))

`if (typeof value === string && value)` ?

**Comment by belozer** [comment]
> > > @belozer @yarastqt а почему бы вот в этом месте
> > > https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92
> > > 
> > > не изменить на `if (value) {` и тогда это решить все наши проблемы?
> > 
> > 
> > @DavyJohnes потому-что, кто-то (не использующий TS) может запихнуть туда `Number, true` и т.д., а так мы явно проверяем на `string`. Я как раз писал именно об этом месте ([#445 (comment)](https://github.com/bem/bem-react/issues/445#issuecomment-510974814))
> 
> `if (typeof value === string && value)` ?

Смысл дополнительно на делать ` && value`  проверку если код в блоке работает со строками?

**Comment by DavyJohnes** [comment]
> > > > @belozer @yarastqt а почему бы вот в этом месте
> > > > https://github.com/bem/bem-react/blob/f10e99bce98bbd563427c7eacc9a8a4ccae07007/packages/classname/classname.tsx#L92
> > > > 
> > > > не изменить на `if (value) {` и тогда это решить все наши проблемы?
> > > 
> > > 
> > > @DavyJohnes потому-что, кто-то (не использующий TS) может запихнуть туда `Number, true` и т.д., а так мы явно проверяем на `string`. Я как раз писал именно об этом месте ([#445 (comment)](https://github.com/bem/bem-react/issues/445#issuecomment-510974814))
> > 
> > 
> > `if (typeof value === string && value)` ?
> 
> Смысл дополнительно делать ` && value` проверку если код в блоке работает со строками?
> 
> upd.
> или это для кейса с пустыми строками `''`?

Да, именно.

**Comment by belozer** [comment]
@DavyJohnes @AleynikovSergey `@bem-react/classname@1.5.3` с фиксом опубликован

**Comment by DavyJohnes** [comment]
Волшебно, спасибо!
