### ISSUE TITLE
Битая ссылка в документации

### ISSUE THREAD

**Issue by f0rmat1k** [bem/bem-react#484]
https://github.com/bem/bem-react/tree/master/docs/ru#состав-пакетов
Все три первые ссылки ведут на 404, например,
https://github.com/bem/bem-react/blob/master/docs/ru/packages/classname/README.md

**Comment by f0rmat1k** [comment]
Тут https://github.com/bem/bem-react/tree/master/docs/en#packages
тоже битые ссылки на доки

**Comment by yarastqt** [comment]
Кажется, что сейчас документация на русском никак не поддерживается и не развивается :(

**Comment by f0rmat1k** [comment]
@yarastqt выше ссылка на англ. версию, там тоже битые ссылки типа такой https://github.com/bem/bem-react/blob/master/docs/en/packages/classname

**Comment by yarastqt** [comment]
А второе — оно работает, но с главной readme :)

**Comment by yarastqt** [comment]
Но вообще можно поправить на фиксированые пути, сделаю

**Comment by veged** [comment]
@yarastqt @tadatuta есть уже повторный тикет #498

**Comment by yarastqt** [comment]
Поправил ссылки тут — https://github.com/bem/bem-react/pull/532
