### ISSUE TITLE
@bem-react/core: Другой способ сбора типов для compose

### ISSUE THREAD

**Issue by yarastqt** [bem/bem-react#493]
## Проблема

В текущей реализации нету возможности указывать обязательные модификаторы, т.к. типы со всех модификаторов собираются через union:

```ts
type CommonProps = {
  checked: boolean
}

type ThemeProps = {
  theme: 'normal'
}

type ResultProps = CommonProps | ThemeProps

const data: ResultProps = { checked: true }
```

Есть ещё одна проблема, с установкой модификатора из переменной:

```ts
const Button = composeU(sizeS, sizeM)(ButtonBase)
const optionalSize = true ? 's' : 'm' // Имеем тип 's' | 'm'
// Получаем ошибку несовместимости типов,
// т.к. в итоговом типе значения размеров находятся в разных интерфейсах
// и имеют такую сигнатуру: { size?: 's' } | { size?: 'm' }
const component = <Button size={optionalSize} />
```

## Что хочется

1. Хочется указывать обязательность модификаторов если они участвуют в композиции.
2. Иметь возможность указывать устанавливать опциональные модификаторы в зависимости от условий.

**Comment by alatielle** [comment]
Привет! Очень больно от второй проблемы, есть ли понимание, когда это будет исправлено?

**Comment by yarastqt** [comment]
Есть такое решение второй проблемы, типы можно собрать другим образом, что в итоге даст профит при выводе типов и их генерации, т.к. мы полностью избавляемся от объединения в результирующем типе:

```ts
export function composeU<t1, t2>(
  fn1: hoc<t1>,
  fn2: hoc<t2>,
): Composition<{ [u in keyof t1]: t1[u] | t2[u] }>
```
 
В итоге мы получим такой тип при композиции (после compose мы больше не имеем объединения и типы выводятся лучше):

```ts
type ThemeAProps = { theme?: 'a' }
type ThemeBProps = { theme?: 'b' }

type Result = {
  theme?: 'a' | 'b' | undefined
}
```

Но тут есть одна проблема, хотя скорее всего это исключение, в кодовой базе нашелся кейс, когда `composeU` используется не с  **простым** модификатором, т.е. этот модификатор не для визуала, он несет в себе ещё какую-то пачку свойств, например:

```ts
type TypeLinkProps = { type?: 'link', href?: string }
type TypeSubmitProps = { type?: 'submit', action?: string }
```

В результате чего текущий вариант перестает работать и мы теряем свойства `href` и `action`, для обхода этого можно придумать какой-нибудь вариант, но как я сказал выше, что это единичный кейс и он является исключением, думаю, что его можно просто переделать. Если все же такие кейсы у кого-то есть, давайте думать про то, как можно улучшить этот вариант.

**Comment by MOTORIST** [comment]
Какова была причина всё оборачивать? Почему сначала не собрать значения модификатора -> прицепить к модификатору -> прицепить модификатор к компоненту (оборачивать если требуется )? 

Написал на коленке простую реализацию (ногами не бейте, много косяков - это только для примера) [ссылка на репозиторий](https://github.com/MOTORIST/bem-core-own-implementationl)

bemModValue() - получает значение модификатора и enhance если требуется.

bemMod() -  получает имя (строку) и массив значений модификатора. Из нее можно получить тип модификатора для изменения (например прокинуть в useState).

withMods()(Component) - получает cnBlock, модификаторы и компонент, оборачивает родительский компонент, если требуется. Если в bemModValue или в bemMod добавить дополнительный параметр settings, то в withMods можно разруливать разную логику.

При такой реализации мы получаем типы модификаторов и не захламляем виртуальный DOM.

**Comment by alatielle** [comment]
> В результате чего текущий вариант перестает работать и мы теряем свойства `href` и `action`, для обхода этого можно придумать какой-нибудь вариант, но как я сказал выше, что это единичный кейс и он является исключением, думаю, что его можно просто переделать. Если все же такие кейсы у кого-то есть, давайте думать про то, как можно улучшить этот вариант.

У нас есть такие кейсы, удобно, когда свойства, нужные только этому модификатору, привязаны к нему.

**Comment by ushakovfserg** [comment]
Привет! Улучшил.
Если есть отличия оборачивает в union, иначе просто мерджит.
```ts
type Intersection<A, B> = A extends B ? A : never;
type Difference<A, B> = A extends B ? never : A;

type CompositionU<T1 extends object, T2 extends object> = Difference<keyof T1, keyof T2> extends never ? {
    [K in Intersection<keyof T1, keyof T2>]: T1[K] | T2[K];
} : T1 | T2;
```

[Ссылка на Playground](https://www.typescriptlang.org/play/index.html?ssl=6&ssc=13&pln=1&pc=1#code/C4TwDgpgBAkgdsCAnAzhAxsAlgezgHgEEAaKAIQD4oBeKQqCAD0TgBMVyoB+OqALihwIAN2QBuALAAoUJCgARLADMlyCHHQQipSjV5MW7TjyGik-OpKnTZ0AMI4AtmBwos2PPgAqARgbN1IxwAIwArDGBSLwAmf0MOEPDMKlpFFTUNLQBrCBAcJShfUhy8gpiqA0COU2RuKABvaShmqABtAGkoLDhYBGQ0TFwCEvzCn2Lc0fKAXQFfDumoAB9C6IWrAF8LX2XVq2kAegOoQHwQQAEQQA4QQB4QQFYQM6hALhBAPhBAZhBAFhBABhAoQEEQJ8BGEAuZw+NyugGkQG5QQD8IGcnpDvqCoNcboA5EEAQiBQJ6owDcIBdAOIgF0A8iBQQBMIFBALwgHz+TzOEOhsN+pIuUDeTyxgDYQMkIv6g1GAGRAMX9AFIgNzeFzJN05UFxdxugHYQKAAVzgQxs4GgXjVABlulkAApIHBgDi0epQWxcAQAcgANjrLaQABZICBKC1QFDAJDdADmUA2qrkGsgAGUFcFHO59YbjQ0zWq3ZaUGGI8B7VAAIaDPBuj1euC+-3WGRqs0QD1+WgOZyudxDbxanVRo1RNWh8ORg1Gij7ItHU6XW73Z7vL6-AFAkHgqEwuEI8WI25ojHYvEXQCcICTyZTqbSZwyA+qHRBHBBCE2Y6bgEeTwn05a-QfCteIGRz3pL8+E8F74XH4gPbElZOC4bgeAQXjPmenYoFEz6vtB3ZAA)

**Comment by MOTORIST** [comment]
Property 'href' does not exist on type 'TypeLinkProps | TypeSubmitProps'.
  Property 'href' does not exist on type 'TypeSubmitProps'

**Comment by yarastqt** [comment]
> Property 'href' does not exist on type 'TypeLinkProps | TypeSubmitProps'.
> Property 'href' does not exist on type 'TypeSubmitProps'

Тут нужно указать, что `type is 'link'`, тогда сможешь обратиться к этому свойсту.

**Comment by yarastqt** [comment]
@ushakovfserg А сможешь сделать пример, как это будет выглядеть на большем кол-ве типов? Я пока не совсем понимаю, как это расширить.

**Comment by MOTORIST** [comment]
@yarastqt  А какая логика должна быть? К примеру:
```
Composition<TypeLinkProps,  ThemeAProps, TypeSubmitProps, ThemeBProps ....>;
```
На выходе:
```
type Result = newTypeMergeThemeAndThemeB | TypeLinkProps | TypeSubmitProps
```

**Comment by ushakovfserg** [comment]
@MOTORIST сделать общий тип композа к сожалению невозможно, остается сделать удовлетворяющий нас тип для `composeU`, чтобы он везде всегда делал union.

[Вот пример для 3х и 4рех](https://www.typescriptlang.org/play/index.html#code/PTAEkIQQBEEBhBCYQReEEBwgtqFYQQQiCkFwghuEEHIgg4iCKiAsILIMIggoiCjqKD8IIHwgsoDgjCCBSIKlukwLABQAFwCeABwCmoACIBLAGZyATAB4AKgEYANKFWKAfKAC8oAKIAPAMYAbAK4ATccoDW44QHs5OraBfvPugwAfU0tbB2dXDx1FbV8ojT0AbgERCWl5OQBmNW9dbVVMg2NZBRUNfP1QYJKlNRidQqr00pz8wuShMUkagBZW6Lb8nqLm2vLooNGy+oLJmrLMobmM6aWm+f7VYfWVzfaBARAIXFRAThAsaBZWQEkQRGpAQRBYBlP79FgUrtAAWXEAJwBzcRlXKVYwAb1AAG0ANKgGQAOx8kU8AAoNE1dABKAC6AC5QGj1BjFJiYdjQABfDqpSQ-AHibLjPINEYQmFwxFxVHo4K6DGZHH4wnE-mk6HkqkfNJ0wF9JkzRY6bbgqGwhFIvwEnnRfkYnqCrVE3mKXW8-VkykdA6dNIAYTcAFtRG4AM7iACqwIqIw28oM4jMgnE8LsLtA8PEADc-qAAPzfP6Ar0TUD47W6amfe1O10exkgtpFASgEujfMVQugANBkNhiPR35xhP08sDFmp4ul30g-2B4Oh8NRmPx7POt2ezaVXmZDv8UtTOqV6v9utDxsjx1jj2rdu8om4zsl32KhJVvu1wcNpuj3MTgr5dSTPlpo066eZu2b29ygsNNaGQ9Rh-Cs-yVXsawHeth2bWVJ0GMDZ3nGpW2ZWYzwg1crw3HNxxQhUnx6RCuwyPC1mXC8oPXUAb1wuCEOnIijxIzYeiXc9ILXa8v1oplWN3HUDznYiFEZGY+LQ8iOKw6juLzRclUrPdUy8EUGLNK1+COQB8EEgRBAB4QVBIGwBhAGYQEhLnuNhEBgVA9MAaRBUFAOhIAYOh7js0B9NQPBMAYdAcEQIhAHkQUBmHgaBWAYSBHOc1zLOYYgSAYHBADYQeAPNYOz0EAGRArk4EhEHgVB0tAAhDNQQB2EFAGx4RkNx4SlSRVC6AAZBEnAABV+NxRDDFUaVjfEAHIrHaobtAAC1+cQ5EG0AXUEX4EX+SlGp0LoAGUbAAIwdGRBC6nq+tACEBuGl0dr2wRxtAABDCxBDq+E5oWpb4RWik1uaiRVHEBbDt6owTtAQQJvEB1xDmka3CsG6ztAIagwWm67FuwRbrm+EbAdbaY0+zSwB0ryjKwUzzNASzWGstB7Jily3I8orPIMnyWH8wLEFOULQHCyLoqc+n4q+sGIYAQQB47TpFyHhtum7IxkcQAHcoYcORbpsKxrtWm0mulgAhCWgal8GZYR7b5cVlXhrVjWtaGkt8ZpHRpdtI3+ulqGLEt5XVZmu3tZ153VGlqR3eB0HTahqQfethHrFul0XRkb2dbWpHBCJYwaO3NRWvaiX8k2y79olpJ07+wQTWz2S72l8Xut6-IDbLj9JAzmca5wuTvvENr4U6xuXSLiQtt20uh5H8Rfv+ofy91kHK8Irut3dRl68Ll3TcNyf1tHkuDrntvF4WgBWIGc-dOUN93kPt83u+Ibd2-Q9bw4ACp3+Ld-QEAPBBWBgNcaAeBQpID0tAJAjlwpOQYPcHAqASBIC5lgM49xv6gHQUTUKdlGA4CKkgYgrByAkAwDQeg6CwToNLJHCGc0ABEt06FNDodtJhwQ6EWDYaAOhUguE1TVgicQdgOigB-qWBWvt8R0NtprQQXCOFWETsnThTR+EzUEcI9B+NREYLnD-LSDBACyIDwPS5BQrQDSgwbQBAeCZQFsQe4JxziOUyjgBgpBCrQD0oFVAji7ihR4C5V4qA6DFXSg8J4Lw3jf2AEAA)

**Comment by yarastqt** [comment]
Проблемы с кол-вом типов на выходе и использованием условий в модификаторах были решены в ПР — https://github.com/bem/bem-react/pull/557
Кейс с обязательными полями в модификаторах пока не ясно как реализовать, закрываю пока этот ишью.
