### ISSUE TITLE
Проблема с логикой в тайпингах

### ISSUE THREAD

**Issue by f0rmat1k** [bem/bem-react#499]
Привет. Написал компонент кнопки на хоках по примеру из readme. Приведу не весь код целиком, а главные его части:

Button_Size_L.ts
```js
interface IButtonSizeLProps {
    size?: ButtonSize.L;
}

export const withSizeL = withBemMod<IButtonSizeLProps, IButtonProps>(
    cnButton(),
    { size: ButtonSize.L }
);
```
Аналогично описан хок Button_Size_M.ts

Использование кнопки:
```js
const Button = compose(
    composeU(
        withSizeL,
        withSizeM
    )
)(ButtonPresenter);

<Button size={ButtonSize.M}>кнопка</Button>
```
Тут все работает хорошо.
Но если добавить логику в пропсу
`<Button size={true ? ButtonSize.M : ButtonSize.L}>кнопка</Button>`, то TS ругается с ошибкой:
```
TS2322: Type '{ children: string; size: ButtonSize.M | ButtonSize.L; }' is not assignable to type '(IntrinsicAttributes & IButtonProps & IButtonSizeLProps & { ...; }) | ... 4 more ... | (IntrinsicAttributes & ... 6 more ... & { ...; })'.
    Type '{ children: string; size: ButtonSize.M | ButtonSize.L; }' is not assignable to type 'IButtonSizeSProps'.
    Types of property 'size' are incompatible.
    Type 'ButtonSize.M | ButtonSize.L' is not assignable to type 'ButtonSize.S'.
    Type 'ButtonSize.M' is not assignable to type 'ButtonSize.S'.
```

Перепробовал разные варианты, никак не получается сделать так, чтоб
1. По умолчанию кнопка не требовала size
2. Если кнопка обернутся в хок(и) размеров, то она начинает требовать size
3. Можно было указывать size с логикой `true ? ButtonSize.M : ButtonSize.L`, если оба нужных хока подключены через composeU

Помогите плз разобраться.

**Comment by yarastqt** [comment]
Тут есть проблема на уровне вывода типов после compose, эта проблема описана в https://github.com/bem/bem-react/issues/493, будем решать её там :(
