### ISSUE TITLE
@bem-react/di: withRegistry spends most of time in `{...props}`

### ISSUE THREAD

**Issue by victor-homyakov** [bem/bem-react#501]
Innocently looking `{...props}` takes most of time while executing `withRegistry`

[The line of code](https://github.com/bem/bem-react/blob/master/packages/di/di.tsx#L32) `<Component {...props} />` is compiled to `React.createElement(Component, __assign({}, props))));`, which makes shallow clone of `props` and passes the copy to `Component`.

How it looks like in profiler:

![image](https://user-images.githubusercontent.com/121449/68992543-d7a3ec80-087d-11ea-84ae-7703748133b7.png)

In fact, `__assign({}, props)` is not needed at all - the code passes received `props` to the nested `<Component />` without any modifications, and `props` isn't used or referenced elsewhere in the code.

**Comment by yarastqt** [comment]
WIll be fixed in linked issue https://github.com/bem/bem-react/issues/476.
