### ISSUE TITLE
@bem-react/core: Remove unused Generics ad add extra where required

### ISSUE THREAD

**Issue by Glazomer** [bem/bem-react#546]
Example of unused ones:
```
function getDisplayName<T>(Component: ComponentType<T> | string) {
  return typeof Component === 'string'
    ? Component
    : Component.displayName || Component.name || 'Component'
}
```

Extra check would be useful in `DisplayNameMeta`, because object passed to a function `getDisplayName`, that only exepts `Component: ComponentType | string`

Example:
```
type DisplayNameMeta = {
  wrapper: any // change all any to  ComponentType
  wrapped: any
  value?: any
}

function setDisplayName(Component: ComponentType<any>, meta: DisplayNameMeta) {
  const wrapperName = getDisplayName(meta.wrapper)
  const wrappedName = getDisplayName(meta.wrapped)

  Component.displayName = `${wrapperName}(${wrappedName})`
  ...
```

**Comment by yarastqt** [comment]
Hello! U can send PR with fixes?

**Comment by Glazomer** [comment]
> Hello! U can send PR with fixes?

Yes, I'll fix it and make a pull request. (working on several issues now)

**Comment by Glazomer** [comment]
> Hello! U can send PR with fixes?
I found this comment in core.ts on line 70
```
// TODO: For performance can rewrite `every` to `for (;;)`.
```
Not sure that this change will make code faster (on benchmarks it shows same result);
