### ISSUE TITLE
Типизация регистра

### ISSUE THREAD

**Issue by psr1919plus21** [bem/bem-react#608]
Вот кейс, который болит:
Определяем регистр:

```ts
const testRegistry = new Registry({
    id: test,
}).fill({
    Avatar: AvatarComponent,
});
```
2. Описываем компонент:
```ts
interface IAvatarComponent {
  id: string;
}
function AvatarComponent(props: IAvatarComponent) { ... }
```
3. Достаем компонент из регистра:
```ts
interface IDesktopLayoutHeaderRegistry {
  Avatar: React.ComponentType<IAvatarComponent>;
}
const {
        Avatar,
    } = useComponentRegistry<IDesktopLayoutHeaderRegistry>('test');
...
<Avatar id={3} />
```
4. Приходит другой разработчик и заменяет компонент в регистре на другой (с другими пропами)

```ts
const testRegistry = new Registry({
    id: test,
}).fill({
    Avatar: () => <div>stub</div>,
});
```

В этот момент хочется, чтобы места в которых используется аватар попадали с ошибкой тайпинга, но этого, очевидно, не происходит.
Можно как-то перенести типизацию в создание регистра?

**Comment by yarastqt** [comment]
Добавил экспорт типа `IRegistryComponents` в версии https://github.com/bem/bem-react/releases/tag/%40bem-react%2Fdi%402.2.8
